apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: biddinggo-api-ingress
  namespace: biddinggo
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - secretName: biddinggo-api-tls-secret
    hosts:
    - biddinggo.jinddd3.synology.me
  rules:
  - host: biddinggo.jinddd3.synology.me
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: biddinggo-api-service
            port:
              number: 8080
