apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-biddinggo-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /Users/jin605/develop/biddinggo-data/mariadb-biddinggo

